title: "InZury"
author: "한인철"
description: "All of <b style=\"color: #3e92b5;\">Gamification</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%Y / %B / %d"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {icon: file, file: "index.html"}
  - {icon: address-card, file: "README.md"}
  - {icon: star, file: "Favorite.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ironin0923@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/InZury"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
